###############################################################################
# modules/approle/main.tf
#
# Creates a single Vault AppRole auth role and generates a bootstrap secret_id.
#
# Resources created:
#   vault_approle_auth_backend_role         — the role definition
#   vault_approle_auth_backend_role_secret_id — a bootstrap secret_id
#
# AppRole auth flow:
#   1. Application provides role_id + secret_id to POST /v1/auth/approle/login
#   2. Vault validates both values and returns a service token
#   3. Application uses the token to call Vault APIs until token_ttl expires
#   4. Before expiry, application calls POST /v1/auth/approle/role/<role>/secret-id
#      (permitted by nwpci-self-secret-id policy) to generate a fresh secret_id
#   5. Application re-authenticates with role_id + new secret_id
#
# Secret_id lifecycle:
#   The bootstrap secret_id is generated by Terraform at role creation time.
#   It is stored in Terraform state and in KV (via the kv_secret module).
#   It MUST be rotated after the first use to ensure state and KV do not
#   hold the live credential.
#
# Token type choice:
#   "default" issues service tokens — they are tracked in Vault's token store,
#   can be renewed, listed, and revoked individually. Use for long-running
#   services and audit-sensitive workloads.
#   "batch" issues lightweight tokens — not tracked, cannot be revoked
#   individually, but have dramatically lower overhead. Use for high-throughput
#   stateless workers that re-authenticate frequently.
###############################################################################

resource "vault_approle_auth_backend_role" "this" {
  # backend must match the path of the vault_auth_backend resource in root/auth.tf.
  backend   = "approle"
  role_name = var.role_name

  # token_policies: list of policy names attached to every token issued by this role.
  # Minimum: nwpci-self-secret-id (self rotation) + one domain policy.
  # Policies are evaluated as a union — a token gets the maximum capabilities
  # of all attached policies.
  token_policies = var.policy_names

  # token_ttl: how long a token issued by this role remains valid.
  # Vault will not automatically renew tokens beyond token_max_ttl.
  # Applications should renew before this elapses or re-authenticate.
  token_ttl = var.token_ttl

  # token_max_ttl: absolute ceiling on token lifetime including renewals.
  # A token cannot be renewed past this value from its creation time.
  # After token_max_ttl elapses, the application must re-authenticate entirely.
  token_max_ttl = var.token_max_ttl

  # secret_id_num_uses: number of times a single secret_id can be exchanged
  # for a token before it is automatically invalidated.
  # 0 = unlimited (appropriate for long-running daemons with infrequent restarts)
  # 1 = single use (maximum security, appropriate for one-shot jobs and CI)
  # For production, consider setting this to 1 and using the self-rotation policy
  # to generate a new secret_id before each job run.
  secret_id_num_uses = var.secret_id_num_uses

  # secret_id_ttl: how long a generated secret_id is valid.
  # "0" means no expiry — the secret_id remains valid until used (if num_uses=1)
  # or until manually revoked. In production, set a finite TTL (e.g. "720h")
  # so stale credentials auto-expire even if rotation tooling fails.
  secret_id_ttl = var.secret_id_ttl

  # secret_id_bound_cidrs: restrict secret_id usage to specific source IP ranges.
  # When set, Vault rejects login attempts from IPs outside these CIDRs even
  # if the role_id and secret_id are valid. Use to lock down automation hosts.
  # Uncomment and set var.bind_secret_id_cidr_list to enable.
  # secret_id_bound_cidrs = var.bind_secret_id_cidr_list

  # token_type: "default" issues service tokens tracked in Vault's token store.
  # Service tokens support renewal, explicit revocation, and token listing.
  # See module header for "batch" token tradeoffs.
  token_type = "default"

  # The AppRole auth backend must exist before roles can be registered.
  # data.vault_auth_backend.approle is the read-only reference to the backend
  # created in root/auth.tf. Declaring it here makes the dependency explicit
  # in the Terraform dependency graph.
  depends_on = [data.vault_auth_backend.approle]
}

resource "vault_approle_auth_backend_role_secret_id" "this" {
  backend   = "approle"
  role_name = vault_approle_auth_backend_role.this.role_name

  # cidr_list: optionally restrict this specific secret_id to source CIDRs.
  # More granular than the role-level secret_id_bound_cidrs — useful when
  # different secret_ids are issued to different automation hosts.
  # cidr_list = var.bind_secret_id_cidr_list

  # metadata: arbitrary JSON string attached to this secret_id for audit purposes.
  # Appears in Vault audit logs alongside login events that use this secret_id.
  # Provides context for incident response — who created it and why.
  # Does NOT affect authentication behaviour.
  metadata = jsonencode({
    created_by  = "terraform"
    role_name   = var.role_name
    description = "Bootstrap secret_id — rotate after first use via self-rotation policy"
  })

  depends_on = [vault_approle_auth_backend_role.this]
}
